import type { MossSystemStatus, MossWorkspace } from '../../src/features/moss/types';

export const mossSystemStatusFixture: MossSystemStatus = {
  schemaVersion: 1,
  availability: 'ready',
  installed: true,
  version: '0.2.2',
  runtimeSha256: 'a'.repeat(64),
  modelSha256: 'b'.repeat(64),
  modelBytes: 2_147_483_648,
  availableDiskBytes: 64_424_509_440,
  deviceName: 'Intel(R) Arc(TM) Graphics',
  health: 'healthy',
  supportsNativeHotwords: false,
  detailCode: null,
  checkedAt: '2026-08-29T08:00:00Z',
};

export function mossWorkspaceFixture(): MossWorkspace {
  const run = {
    runId: 'run-1',
    meetingId: 'meeting-1',
    state: 'completed' as const,
    progress: { stage: 'complete' as const, percentage: 100 },
    createdAt: '2026-08-29T08:00:00Z',
    updatedAt: '2026-08-29T08:05:00Z',
    completedAt: '2026-08-29T08:05:00Z',
    errorCode: null,
    canCancel: false,
    candidateRevision: 3,
    candidateSha256: 'c'.repeat(64),
    languageRequested: 'zh-CN',
    languageResolved: 'zh-CN',
    decodeParametersJson: '{"language":"zh","timestamps":"segment","diarize":"on"}',
    decodeParametersSha256: '1b8ee2dde060ce156ff43cd9b08a19f54060018bab428373b7094ee887e0d47e',
  };
  return {
    schemaVersion: 1,
    meetingId: 'meeting-1',
    system: structuredClone(mossSystemStatusFixture),
    runs: [run],
    selectedRunId: 'run-1',
    review: {
      schemaVersion: 1,
      meetingId: 'meeting-1',
      run,
      current: {
        source: 'whisper',
        revision: 7,
        sha256: 'd'.repeat(64),
        segments: [{
          segmentId: 'current-1',
          startMs: 0,
          endMs: 3000,
          speakerLabel: null,
          text: '现行文字',
          resolvedPersonId: null,
          segmentOverridePersonId: null,
          speakerResolution: 'anonymous',
          textSourceLayer: 'current_transcript',
        }],
      },
      candidate: {
        source: 'moss',
        runId: 'run-1',
        revision: 3,
        sha256: 'c'.repeat(64),
        isActive: false,
        segments: [
          {
            segmentId: 'candidate-1',
            startMs: 0,
            endMs: 1500,
            speakerLabel: 'S01',
            text: '西吉艾斯进度正常',
            resolvedPersonId: null,
            segmentOverridePersonId: null,
            speakerResolution: 'anonymous',
            textSourceLayer: 'context_correction',
          },
          {
            segmentId: 'candidate-2',
            startMs: 1500,
            endMs: 3000,
            speakerLabel: 'S02',
            text: 'CGS 进度正常',
            resolvedPersonId: null,
            segmentOverridePersonId: null,
            speakerResolution: 'anonymous',
            textSourceLayer: 'raw_moss',
          },
          {
            segmentId: 'candidate-3',
            startMs: 3000,
            endMs: 4500,
            speakerLabel: 'S01',
            text: 'Ben 人工绑定片段',
            resolvedPersonId: 'person-ben',
            segmentOverridePersonId: 'person-ben',
            speakerResolution: 'segment_override',
            textSourceLayer: 'raw_moss',
          },
        ],
        alignments: [
          {
            segmentId: 'candidate-1',
            rawSegmentIndex: 0,
            rawStartMs: 0,
            rawEndMs: 1500,
            rawTextSha256: 'e'.repeat(64),
            alignmentMethod: 'moss_segment',
            confidence: null,
            sourceAnchorIds: [],
            sourceTranscriptSha256: 'd'.repeat(64),
            audioTokenTrackSha256: null,
            firstAudioTokenIndex: null,
            lastAudioTokenIndex: null,
          },
          {
            segmentId: 'candidate-2',
            rawSegmentIndex: 1,
            rawStartMs: 1500,
            rawEndMs: 3000,
            rawTextSha256: 'f'.repeat(64),
            alignmentMethod: 'source_transcript_segment',
            confidence: 0.92,
            sourceAnchorIds: ['current-1'],
            sourceTranscriptSha256: 'd'.repeat(64),
            audioTokenTrackSha256: null,
            firstAudioTokenIndex: null,
            lastAudioTokenIndex: null,
          },
          {
            segmentId: 'candidate-3',
            rawSegmentIndex: 2,
            rawStartMs: 3000,
            rawEndMs: 4500,
            rawTextSha256: '0'.repeat(64),
            alignmentMethod: 'moss_segment',
            confidence: null,
            sourceAnchorIds: [],
            sourceTranscriptSha256: 'd'.repeat(64),
            audioTokenTrackSha256: null,
            firstAudioTokenIndex: null,
            lastAudioTokenIndex: null,
          },
        ],
        diagnostics: {
          audioDurationMs: 5000,
          activityFrameMs: 20,
          activityThresholdDbfs: -50,
          firstActiveMs: 0,
          lastActiveMs: 4500,
          modelLastTimestampMs: 4550,
          tailDeltaMs: 50,
          alignedSegmentCount: 1,
          fallbackSegmentCount: 2,
          sourceAnchorCount: 1,
          sourceHashVerified: true,
          sourceExpectedSha256: 'd'.repeat(64),
          sourceActualSha256: 'd'.repeat(64),
          fallbackReason: 'PARTIAL_ALIGNMENT_FALLBACK',
        },
        audioTokenAlignment: null,
      },
      participants: [{
        personId: 'person-ben',
        displayName: 'Ben',
        attendance: 'attending',
        department: null,
        role: null,
      }],
      anonymousSpeakers: ['S01', 'S02'],
      bindings: [
        { speakerLabel: 'S01', personId: null },
        { speakerLabel: 'S02', personId: null },
      ],
      corrections: [{
        correctionId: 'correction-1',
        segmentId: 'candidate-1',
        originalText: '西吉艾斯进度正常',
        correctedText: 'CGS 进度正常',
        matchedAlias: '西吉艾斯',
        canonical: 'CGS',
        ruleId: 'term-cgs-alias-1',
        contextRevision: 2,
        state: 'applied',
        sourceLayer: 'context_alias',
        machineSource: null,
      }],
      activation: {
        activeRunId: null,
        activeActivationId: null,
        currentTranscriptSha256: 'd'.repeat(64),
        canActivate: true,
        activateBlocker: null,
        canRollback: false,
      },
    },
  };
}
